---

# global settings
image: alpine:latest
stages:
  - linter

.only-default: &only-default
  only:
    - master
    - merge_requests
    - tags

mr-settings:
  stage: linter
  only:
    - merge_requests
  before_script:
    - apk -q add python3
  script:
    - wget -q "https://gitlab.com/postmarketOS/ci-common/-/raw/master/check_mr_settings.py"
    - python3 ./check_mr_settings.py

shellcheck:
  stage: linter
  <<: *only-default
  before_script:
    - apk -q add shellcheck git
  script:
    - .gitlab-ci/shellcheck.sh
